#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'exomy','console_scripts','robot_node_modified'
__requires__ = 'exomy'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('exomy', 'console_scripts', 'robot_node_modified')()
    )
